{{- if .Values.secrets.enabled -}}
{{- $name := include "lara-indexer.fullname" . -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $name) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lara-indexer.fullname" . }}
  labels:
    {{- include "lara-indexer.labels" . | nindent 4 }}
type: Opaque
data:
{{ if $secret }}
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{ else }}
  PRIVATE_KEY: {{ .Values.secrets.privateKey | b64enc | quote }}
{{- end }}
{{- end }}
