apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lara-indexer.fullname" . }}
  labels:
    {{- include "lara-indexer.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "lara-indexer.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lara-indexer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lara-indexer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-lara
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
          - secretRef:
              name: {{ include "lara-indexer.fullname" . }}
        command:
        - /taraxa-indexer
        args:
        {{- include "lara-indexer.args" . | nindent 8 }}
        - -lara_enabled
        volumeMounts:
        - name: indexer-data
          mountPath: {{ .Values.indexer.dataDir }}
      - name: {{ .Chart.Name }}-indexer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
          - secretRef:
              name: {{ include "lara-indexer.fullname" . }}
        command:
        - /taraxa-indexer
        args:
        {{- include "lara-indexer.args" . | nindent 8 }}
        volumeMounts:
        - name: indexer-data
          mountPath: {{ .Values.indexer.dataDir }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: indexer-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.storage.size }}